"""
Interface text, per language.

The language picker was cosmetic before: it set the microphone's input language
and nothing else, so tapping a Bengali suggestion always produced a Bengali
answer no matter what the picker said. Fixing that properly means the whole
interface — labels, suggested questions, verdict badges — has to exist in each
language, not just the sentences the risk agent produces.
"""

from __future__ import annotations

UI: dict[str, dict] = {
    "bn": {
        "tagline": "সমুদ্রে যাওয়ার আগে জিজ্ঞেস করুন",
        "hint": "যা জানতে চান, বলুন বা বেছে নিন",
        "mic": "চেপে ধরে বলুন",
        "listening": "শুনছি…",
        "mic_fail": "শোনা গেল না, আবার চেষ্টা করুন",
        "no_voice": "এই ব্রাউজারে ভয়েস চলবে না — Chrome ব্যবহার করুন",
        "replay": "আবার শুনুন",
        "because": "কেন এই উত্তর",
        "carried": "আগের প্রশ্ন থেকে ধরে রাখা",
        "working": "এজেন্টরা তথ্য মেলাচ্ছে…",
        "failed": "তথ্য আনা গেল না।",
        "none": "কোনো তথ্য পাওয়া যায়নি।",
        "boat_label": "নৌকার দৈর্ঘ্য (মিটার)",
        "map_credit": "মানচিত্র © OpenStreetMap · সীমানা আনুমানিক",
        "watch_on": "সমুদ্রে থাকাকালীন সতর্ক করুন",
        "watch_active": "সতর্কতা চালু — অবস্থা খারাপ হলে জানাব",
        "alert_title": "সতর্কতা",
        "verdict": {"go": "নিরাপদ", "caution": "সতর্ক থাকুন", "stay": "যাবেন না", "unknown": "তথ্য নেই"},
        "starters": ["কাল সকালে যাওয়া নিরাপদ?", "আজ সমুদ্র কেমন?",
                     "কাছে মাছ কোথায়?"],
        "follow": ["আর পরশু?", "নৌকা ১৮ মিটার হলে?", "সীমানা কত দূরে?",
                   "কাছে মাছ কোথায়?"],
    },
    "hi": {
        "tagline": "समुद्र में जाने से पहले पूछें",
        "hint": "जो जानना है, बोलें या चुनें",
        "mic": "दबाकर बोलें",
        "listening": "सुन रहे हैं…",
        "mic_fail": "सुनाई नहीं दिया, फिर कोशिश करें",
        "no_voice": "इस ब्राउज़र में आवाज़ नहीं चलेगी — Chrome इस्तेमाल करें",
        "replay": "फिर सुनें",
        "because": "यह उत्तर क्यों",
        "carried": "पिछले सवाल से लिया गया",
        "working": "एजेंट जानकारी मिला रहे हैं…",
        "failed": "जानकारी नहीं मिल सकी।",
        "none": "कोई जानकारी नहीं मिली।",
        "boat_label": "नाव की लंबाई (मीटर)",
        "map_credit": "मानचित्र © OpenStreetMap · सीमा अनुमानित",
        "watch_on": "समुद्र में रहते हुए सचेत करें",
        "watch_active": "सतर्कता चालू — स्थिति बिगड़ने पर बताएँगे",
        "alert_title": "चेतावनी",
        "verdict": {"go": "सुरक्षित", "caution": "सावधान रहें", "stay": "मत जाइए", "unknown": "जानकारी नहीं"},
        "starters": ["कल सुबह जाना सुरक्षित है?", "आज समुद्र कैसा है?",
                     "पास मछली कहाँ है?"],
        "follow": ["और परसों?", "नाव 18 मीटर हो तो?", "सीमा कितनी दूर है?",
                   "पास मछली कहाँ है?"],
    },
    "mr": {
        "tagline": "समुद्रात जाण्यापूर्वी विचारा",
        "hint": "काय जाणून घ्यायचे आहे, बोला किंवा निवडा",
        "mic": "दाबून बोला",
        "listening": "ऐकत आहोत…",
        "mic_fail": "ऐकू आले नाही, पुन्हा प्रयत्न करा",
        "no_voice": "या ब्राउझरमध्ये आवाज चालणार नाही — Chrome वापरा",
        "replay": "पुन्हा ऐका",
        "because": "हे उत्तर का",
        "carried": "मागील प्रश्नातून घेतले",
        "working": "एजंट माहिती जुळवत आहेत…",
        "failed": "माहिती मिळाली नाही.",
        "none": "काहीही माहिती मिळाली नाही.",
        "boat_label": "नावेची लांबी (मीटर)",
        "map_credit": "नकाशा © OpenStreetMap · सीमा अंदाजे",
        "watch_on": "समुद्रात असताना सावध करा",
        "watch_active": "सतर्कता चालू — स्थिती बिघडल्यास सांगू",
        "alert_title": "इशारा",
        "verdict": {"go": "सुरक्षित", "caution": "सावध रहा", "stay": "जाऊ नका", "unknown": "माहिती नाही"},
        "starters": ["उद्या सकाळी जाणे सुरक्षित आहे?", "आज समुद्र कसा आहे?",
                     "जवळ मासे कुठे आहेत?"],
        "follow": ["आणि परवा?", "नाव 18 मीटर असेल तर?", "सीमा किती दूर आहे?",
                   "जवळ मासे कुठे आहेत?"],
    },
    "gu": {
        "tagline": "દરિયામાં જતાં પહેલાં પૂછો",
        "hint": "જે જાણવું છે તે બોલો અથવા પસંદ કરો",
        "mic": "દબાવીને બોલો",
        "listening": "સાંભળી રહ્યા છીએ…",
        "mic_fail": "સંભળાયું નહીં, ફરી પ્રયાસ કરો",
        "no_voice": "આ બ્રાઉઝરમાં અવાજ ચાલશે નહીં — Chrome વાપરો",
        "replay": "ફરી સાંભળો",
        "because": "આ જવાબ કેમ",
        "carried": "પાછલા પ્રશ્નમાંથી લીધેલું",
        "working": "એજન્ટ માહિતી મેળવી રહ્યા છે…",
        "failed": "માહિતી મળી શકી નહીં.",
        "none": "કોઈ માહિતી મળી નથી.",
        "boat_label": "હોડીની લંબાઈ (મીટર)",
        "map_credit": "નકશો © OpenStreetMap · સીમા અંદાજિત",
        "watch_on": "દરિયામાં હોઉં ત્યારે ચેતવો",
        "watch_active": "ચેતવણી ચાલુ — સ્થિતિ બગડે તો જણાવીશું",
        "alert_title": "ચેતવણી",
        "verdict": {"go": "સલામત", "caution": "સાવધ રહો", "stay": "જશો નહીં", "unknown": "માહિતી નથી"},
        "starters": ["કાલે સવારે જવું સલામત છે?", "આજે દરિયો કેવો છે?",
                     "નજીક માછલી ક્યાં છે?"],
        "follow": ["અને પરમ દિવસે?", "હોડી 18 મીટર હોય તો?", "સીમા કેટલી દૂર છે?",
                   "નજીક માછલી ક્યાં છે?"],
    },
    "or": {
        "tagline": "ସମୁଦ୍ରକୁ ଯିବା ପୂର୍ବରୁ ପଚାରନ୍ତୁ",
        "hint": "ଯାହା ଜାଣିବାକୁ ଚାହାଁନ୍ତି, କୁହନ୍ତୁ କିମ୍ବା ବାଛନ୍ତୁ",
        "mic": "ଚାପି ଧରି କୁହନ୍ତୁ",
        "listening": "ଶୁଣୁଛୁ…",
        "mic_fail": "ଶୁଣିପାରିଲୁ ନାହିଁ, ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ",
        "no_voice": "ଏହି ବ୍ରାଉଜରରେ ଭଏସ ଚାଲିବ ନାହିଁ — Chrome ବ୍ୟବହାର କରନ୍ତୁ",
        "replay": "ପୁଣି ଶୁଣନ୍ତୁ",
        "because": "ଏହି ଉତ୍ତର କାହିଁକି",
        "carried": "ପୂର୍ବ ପ୍ରଶ୍ନରୁ ନିଆଯାଇଛି",
        "working": "ଏଜେଣ୍ଟମାନେ ତଥ୍ୟ ମେଳାଉଛନ୍ତି…",
        "failed": "ତଥ୍ୟ ଆଣିହେଲା ନାହିଁ।",
        "none": "କୌଣସି ତଥ୍ୟ ମିଳିଲା ନାହିଁ।",
        "boat_label": "ଡଙ୍ଗାର ଲମ୍ବ (ମିଟର)",
        "map_credit": "ମାନଚିତ୍ର © OpenStreetMap · ସୀମା ଆନୁମାନିକ",
        "watch_on": "ସମୁଦ୍ରରେ ଥିବାବେଳେ ସତର୍କ କରନ୍ତୁ",
        "watch_active": "ସତର୍କତା ଚାଲୁ — ଅବସ୍ଥା ଖରାପ ହେଲେ ଜଣାଇବୁ",
        "alert_title": "ସତର୍କତା",
        "verdict": {"go": "ନିରାପଦ", "caution": "ସତର୍କ ରୁହନ୍ତୁ", "stay": "ଯିବେ ନାହିଁ", "unknown": "ତଥ୍ୟ ନାହିଁ"},
        "starters": ["କାଲି ସକାଳେ ଯିବା ନିରାପଦ କି?", "ଆଜି ସମୁଦ୍ର କେମିତି?",
                     "ନିକଟରେ ମାଛ କେଉଁଠି?"],
        "follow": ["ଆଉ ପରଦିନ?", "ଡଙ୍ଗା 18 ମିଟର ହେଲେ?", "ସୀମା କେତେ ଦୂର?",
                   "ନିକଟରେ ମାଛ କେଉଁଠି?"],
    },
    "ta": {
        "tagline": "கடலுக்குச் செல்வதற்கு முன் கேளுங்கள்",
        "hint": "தெரிந்து கொள்ள வேண்டியதைச் சொல்லுங்கள் அல்லது தேர்ந்தெடுங்கள்",
        "mic": "அழுத்திப் பேசுங்கள்",
        "listening": "கேட்டுக் கொண்டிருக்கிறோம்…",
        "mic_fail": "கேட்கவில்லை, மீண்டும் முயலுங்கள்",
        "no_voice": "இந்த உலாவியில் குரல் இயங்காது — Chrome பயன்படுத்துங்கள்",
        "replay": "மீண்டும் கேளுங்கள்",
        "because": "இந்த பதில் ஏன்",
        "carried": "முந்தைய கேள்வியிலிருந்து எடுக்கப்பட்டது",
        "working": "முகவர்கள் தகவலை ஒப்பிடுகின்றனர்…",
        "failed": "தகவல் கிடைக்கவில்லை.",
        "none": "எந்த தகவலும் கிடைக்கவில்லை.",
        "boat_label": "படகின் நீளம் (மீட்டர்)",
        "map_credit": "வரைபடம் © OpenStreetMap · எல்லை தோராயமானது",
        "watch_on": "கடலில் இருக்கும்போது எச்சரிக்கவும்",
        "watch_active": "எச்சரிக்கை இயக்கத்தில் — நிலை மோசமானால் தெரிவிப்போம்",
        "alert_title": "எச்சரிக்கை",
        "verdict": {"go": "பாதுகாப்பானது", "caution": "எச்சரிக்கையாக இருங்கள்", "stay": "போக வேண்டாம்", "unknown": "தகவல் இல்லை"},
        "starters": ["நாளை காலை போவது பாதுகாப்பானதா?", "இன்று கடல் எப்படி உள்ளது?",
                     "அருகில் மீன் எங்கே?"],
        "follow": ["நாளை மறுநாள்?", "படகு 18 மீட்டர் என்றால்?", "எல்லை எவ்வளவு தூரம்?",
                   "அருகில் மீன் எங்கே?"],
    },
    "te": {
        "tagline": "సముద్రంలోకి వెళ్లే ముందు అడగండి",
        "hint": "తెలుసుకోవాలనుకున్నది చెప్పండి లేదా ఎంచుకోండి",
        "mic": "నొక్కి మాట్లాడండి",
        "listening": "వింటున్నాము…",
        "mic_fail": "వినిపించలేదు, మళ్లీ ప్రయత్నించండి",
        "no_voice": "ఈ బ్రౌజర్‌లో వాయిస్ పనిచేయదు — Chrome వాడండి",
        "replay": "మళ్లీ వినండి",
        "because": "ఈ సమాధానం ఎందుకు",
        "carried": "మునుపటి ప్రశ్న నుండి తీసుకున్నది",
        "working": "ఏజెంట్లు సమాచారం సరిపోల్చుతున్నారు…",
        "failed": "సమాచారం తీసుకురాలేకపోయాము.",
        "none": "ఎటువంటి సమాచారం దొరకలేదు.",
        "boat_label": "పడవ పొడవు (మీటర్లు)",
        "map_credit": "మ్యాప్ © OpenStreetMap · సరిహద్దు అంచనా",
        "watch_on": "సముద్రంలో ఉన్నప్పుడు హెచ్చరించండి",
        "watch_active": "హెచ్చరిక ఆన్ — పరిస్థితి దిగజారితే చెబుతాం",
        "alert_title": "హెచ్చరిక",
        "verdict": {"go": "సురక్షితం", "caution": "జాగ్రత్తగా ఉండండి", "stay": "వెళ్లవద్దు", "unknown": "సమాచారం లేదు"},
        "starters": ["రేపు ఉదయం వెళ్లడం సురక్షితమా?", "ఈరోజు సముద్రం ఎలా ఉంది?",
                     "దగ్గరలో చేపలు ఎక్కడ?"],
        "follow": ["మరి ఎల్లుండి?", "పడవ 18 మీటర్లు అయితే?", "సరిహద్దు ఎంత దూరం?",
                   "దగ్గరలో చేపలు ఎక్కడ?"],
    },
    "ml": {
        "tagline": "കടലിൽ പോകുന്നതിന് മുൻപ് ചോദിക്കുക",
        "hint": "അറിയേണ്ടത് പറയുക അല്ലെങ്കിൽ തിരഞ്ഞെടുക്കുക",
        "mic": "അമർത്തി പറയുക",
        "listening": "കേൾക്കുന്നു…",
        "mic_fail": "കേട്ടില്ല, വീണ്ടും ശ്രമിക്കുക",
        "no_voice": "ഈ ബ്രൗസറിൽ ശബ്ദം പ്രവർത്തിക്കില്ല — Chrome ഉപയോഗിക്കുക",
        "replay": "വീണ്ടും കേൾക്കുക",
        "because": "ഈ ഉത്തരം എന്തുകൊണ്ട്",
        "carried": "മുൻ ചോദ്യത്തിൽ നിന്ന് എടുത്തത്",
        "working": "ഏജന്റുകൾ വിവരം ഒത്തുനോക്കുന്നു…",
        "failed": "വിവരം ലഭിച്ചില്ല.",
        "none": "ഒരു വിവരവും ലഭിച്ചില്ല.",
        "boat_label": "വള്ളത്തിന്റെ നീളം (മീറ്റർ)",
        "map_credit": "ഭൂപടം © OpenStreetMap · അതിർത്തി ഏകദേശം",
        "watch_on": "കടലിലായിരിക്കുമ്പോൾ അറിയിക്കുക",
        "watch_active": "അറിയിപ്പ് ഓൺ — സ്ഥിതി മോശമായാൽ പറയും",
        "alert_title": "മുന്നറിയിപ്പ്",
        "verdict": {"go": "സുരക്ഷിതം", "caution": "ജാഗ്രത പാലിക്കുക", "stay": "പോകരുത്", "unknown": "വിവരമില്ല"},
        "starters": ["നാളെ രാവിലെ പോകുന്നത് സുരക്ഷിതമാണോ?", "ഇന്ന് കടൽ എങ്ങനെയുണ്ട്?",
                     "അടുത്ത് മീൻ എവിടെ?"],
        "follow": ["മറ്റന്നാൾ?", "വള്ളം 18 മീറ്റർ ആണെങ്കിൽ?", "അതിർത്തി എത്ര അകലെ?",
                   "അടുത്ത് മീൻ എവിടെ?"],
    },
}

UI["en"] = {
    "tagline": "Ask before you go out",
    "hint": "Say what you need to know, or pick one",
    "mic": "Hold and speak",
    "listening": "Listening…",
    "mic_fail": "Did not catch that, try again",
    "no_voice": "Voice will not work in this browser — use Chrome",
    "replay": "Play again",
    "because": "Why this answer",
    "carried": "carried from your last question",
    "working": "Agents are correlating sources…",
    "failed": "Could not fetch data.",
    "none": "No data available.",
    "boat_label": "Boat length (m)",
    "map_credit": "Map © OpenStreetMap · boundary is approximate",
    "watch_on": "Alert me while I am at sea",
    "watch_active": "Watching — we will tell you if it turns",
    "alert_title": "Warning",
    "verdict": {"go": "Safe", "caution": "Take care", "stay": "Do not go",
                "unknown": "No data"},
    "starters": ["Is tomorrow morning safe?", "How is the sea today?",
                 "Where are the fish nearby?"],
    "follow": ["And the day after?", "What if my boat is 18 m?",
               "How far is the boundary?", "Where are the fish nearby?"],
}


def strings(lang: str) -> dict:
    return UI.get(lang, UI["bn"])
